# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import command_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='pb',
  serialized_pb='\n\x0cserver.proto\x12\x02pb\x1a\rcommand.proto*\xbd\x02\n\tSerOpcode\x12\x14\n\x0fGMSG_ENTER_ROOM\x10\x90N\x12\x14\n\x0fGMSG_LEAVE_ROOM\x10\x91N\x12\x17\n\x12GMSG_ADMIN_OPERATE\x10\x92N\x12\x1b\n\x16GMSG_CHANGE_USR_STATUS\x10\x93N\x12\x18\n\x13GMSG_KICK_FROM_GATE\x10\x94N\x12\x12\n\rGMSG_ON_LOGIN\x10\x95N\x12\x14\n\x0fGMSG_GM_COMMAND\x10\x96N\x12\x18\n\x13GMSG_ADMIN_ANALYSIS\x10\x97N\x12\x13\n\x0eGMSG_AUTHORIZE\x10\x98N\x12\x17\n\x12GMSG_ON_LOAD_READY\x10\x99N\x12\x15\n\x10GMSG_PAY_COMMAND\x10\x9aN\x12\x15\n\x10GMSG_OTHER_LOGIN\x10\x9bN\x12\x14\n\x0fGMSG_ONLY_LOGIN\x10\x9cN')

_SEROPCODE = _descriptor.EnumDescriptor(
  name='SerOpcode',
  full_name='pb.SerOpcode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GMSG_ENTER_ROOM', index=0, number=10000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_LEAVE_ROOM', index=1, number=10001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_ADMIN_OPERATE', index=2, number=10002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_CHANGE_USR_STATUS', index=3, number=10003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_KICK_FROM_GATE', index=4, number=10004,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_ON_LOGIN', index=5, number=10005,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_GM_COMMAND', index=6, number=10006,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_ADMIN_ANALYSIS', index=7, number=10007,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_AUTHORIZE', index=8, number=10008,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_ON_LOAD_READY', index=9, number=10009,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_PAY_COMMAND', index=10, number=10010,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_OTHER_LOGIN', index=11, number=10011,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMSG_ONLY_LOGIN', index=12, number=10012,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=36,
  serialized_end=353,
)

SerOpcode = enum_type_wrapper.EnumTypeWrapper(_SEROPCODE)
GMSG_ENTER_ROOM = 10000
GMSG_LEAVE_ROOM = 10001
GMSG_ADMIN_OPERATE = 10002
GMSG_CHANGE_USR_STATUS = 10003
GMSG_KICK_FROM_GATE = 10004
GMSG_ON_LOGIN = 10005
GMSG_GM_COMMAND = 10006
GMSG_ADMIN_ANALYSIS = 10007
GMSG_AUTHORIZE = 10008
GMSG_ON_LOAD_READY = 10009
GMSG_PAY_COMMAND = 10010
GMSG_OTHER_LOGIN = 10011
GMSG_ONLY_LOGIN = 10012




# @@protoc_insertion_point(module_scope)
